
---

    - block:

      - name: Uninstall Provider
        package: name='CARKaim' state=absent

      - name: Logon to CyberArk Vault using PAS Web Services SDK - use_shared_logon_authentication
        cyberark_authentication:
          api_base_url: "{{ api_base_url }}"
          use_shared_logon_authentication: true
          validate_certs: "{{ validate_certs }}"
        when: (use_shared_logon_authentication)

      - name: Logon to CyberArk Vault using PAS Web Services SDK - Not use_shared_logon_authentication
        cyberark_authentication:
          api_base_url: "{{ api_base_url }}"
          username: '{{ lookup("cyberarkpassword", {"appid": "ansible", "query": "safe=impact-2018;folder=root;object=Application-CyberArk-10.25.10.5-Administrator", "output": "UserName"}) }}'
          password: '{{ lookup("cyberarkpassword", {"appid": "ansible", "query": "safe=impact-2018;folder=root;object=Application-CyberArk-10.25.10.5-Administrator", "output": "Password"}) }}'
          use_shared_logon_authentication: false
          validate_certs: "{{ validate_certs }}"
        changed_when: false
        when: (not use_shared_logon_authentication)

      # name: Debug message
      #  debug:
      #    msg: "{{ cyberark_session }}"
      #  when: (cyberark_session.token is defined)

      - name: Remove Provider User
        cyberark_user:
          username: "Prov_{{ansible_hostname}}"
          state: absent
          cyberark_session: "{{ cyberark_session }}"
        register: cyberarkaction
        ignore_errors: yes
        when: (cyberark_session.token is defined)

      # debug:
      #    msg: "USERDETAILS => {{cyberarkaction}}"
      #  when: (cyberarkaction.status_code == 200)

      - name: Logoff from CyberArk Vault
        cyberark_authentication:
          state: absent
          cyberark_session: "{{ cyberark_session }}"
        changed_when: false
        when: (cyberark_session.token is defined)

      - name: Remove /etc/opt/CARKaim
        file:
          path: '/etc/opt/CARKaim'
          state: absent

      - name: Remove /var/opt/CARKaim
        file:
          path: '/var/opt/CARKaim'
          state: absent

      rescue:

        - fail:
            msg: "AIM Credential Provider Uninstall failed!"
